name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find Flutter project
        id: find_project
        run: |
          echo "Looking for pubspec.yaml files..."
          find . -name "pubspec.yaml" -type f
          
          # Find the first pubspec.yaml file and get its directory
          PUBSPEC_PATH=$(find . -name "pubspec.yaml" -type f | head -1)
          if [ -z "$PUBSPEC_PATH" ]; then
            echo "No pubspec.yaml found!"
            exit 1
          fi
          
          PROJECT_DIR=$(dirname "$PUBSPEC_PATH")
          echo "Flutter project found in: $PROJECT_DIR"
          echo "project_dir=$PROJECT_DIR" >> $GITHUB_OUTPUT
          
          # List the contents of the project directory
          echo "Project directory contents:"
          ls -la "$PROJECT_DIR"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'
          channel: 'stable'

      - name: Enable web support
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ steps.find_project.outputs.project_dir }}

      - name: Build Flutter Web
        run: flutter build web --release --web-renderer html
        working-directory: ${{ steps.find_project.outputs.project_dir }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.find_project.outputs.project_dir }}/build/web

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4